/*
 * Copyright 2023-2025 Trustify Dependency Analytics Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.guacsec.trustifyda.providers;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.github.guacsec.trustifyda.tools.Ecosystem;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Tests for CargoProvider lock file validation functionality. These tests use
 * Ecosystem.getProvider() to trigger the validateLockFile method.
 */
public class CargoProviderLockFileValidationTest {

  @Test
  public void testLockFileValidationWithMissingLockFile(@TempDir Path tempDir) throws IOException {
    // Create a valid Cargo.toml without Cargo.lock
    Path cargoToml = tempDir.resolve("Cargo.toml");
    String content =
        """
        [package]
        name = "test-project"
        version = "1.0.0"
        edition = "2021"

        [dependencies]
        serde = "1.0"
        """;
    Files.writeString(cargoToml, content);

    // Should throw IllegalStateException when calling getProvider (which calls validateLockFile)
    IllegalStateException exception =
        assertThrows(
            IllegalStateException.class,
            () -> Ecosystem.getProvider(cargoToml),
            "Should throw IllegalStateException for missing Cargo.lock");

    assertTrue(exception.getMessage().contains("Cargo.lock does not exist"));
    assertTrue(exception.getMessage().contains("cargo build"));

    System.out.println("✓ Missing lock file validation test passed!");
  }

  @Test
  public void testLockFileValidationWithValidLockFile(@TempDir Path tempDir) throws IOException {
    // Create a valid Cargo.toml
    Path cargoToml = tempDir.resolve("Cargo.toml");
    String content =
        """
        [package]
        name = "test-project"
        version = "1.0.0"
        edition = "2021"

        [dependencies]
        serde = "1.0"
        """;
    Files.writeString(cargoToml, content);

    // Create a valid Cargo.lock
    Path cargoLock = tempDir.resolve("Cargo.lock");
    String lockContent =
        """
        # This file is automatically @generated by Cargo.
        # It is not intended for manual editing.
        version = 3

        [[package]]
        name = "test-project"
        version = "1.0.0"
        dependencies = [
         "serde",
        ]

        [[package]]
        name = "serde"
        version = "1.0.136"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "13bd41f6daf2677b5378d5aefb23b3b28ad25c27"
        """;
    Files.writeString(cargoLock, lockContent);

    // Should not throw exception for valid lock file
    assertDoesNotThrow(
        () -> Ecosystem.getProvider(cargoToml), "Should not throw exception for valid Cargo.lock");

    System.out.println("✓ Valid lock file validation test passed!");
  }

  @Test
  public void testLockFileValidationWithWorkspaceScenario(@TempDir Path tempDir)
      throws IOException {
    // Create workspace structure:
    // tempDir/
    //   ├── Cargo.toml (workspace)
    //   ├── Cargo.lock
    //   └── member1/
    //       └── Cargo.toml (member crate)

    // Create workspace Cargo.toml
    Path workspaceCargoToml = tempDir.resolve("Cargo.toml");
    String workspaceContent =
        """
        [workspace]
        members = ["member1"]

        [workspace.package]
        version = "1.0.0"
        edition = "2021"
        """;
    Files.writeString(workspaceCargoToml, workspaceContent);

    // Create workspace Cargo.lock
    Path workspaceCargoLock = tempDir.resolve("Cargo.lock");
    String lockContent =
        """
        # This file is automatically @generated by Cargo.
        # It is not intended for manual editing.
        version = 3

        [[package]]
        name = "member1"
        version = "1.0.0"
        """;
    Files.writeString(workspaceCargoLock, lockContent);

    // Create member directory and Cargo.toml
    Path memberDir = tempDir.resolve("member1");
    Files.createDirectories(memberDir);
    Path memberCargoToml = memberDir.resolve("Cargo.toml");
    String memberContent =
        """
        [package]
        name = "member1"
        version = { workspace = true }
        edition = { workspace = true }

        [dependencies]
        serde = "1.0"
        """;
    Files.writeString(memberCargoToml, memberContent);

    // Should find workspace lock file even when called with member crate
    assertDoesNotThrow(
        () -> Ecosystem.getProvider(memberCargoToml),
        "Should find workspace Cargo.lock from member crate");

    System.out.println("✓ Workspace lock file validation test passed!");
  }

  @Test
  public void testLockFileValidationWithMissingLockInWorkspace(@TempDir Path tempDir)
      throws IOException {
    // Create workspace structure without Cargo.lock to test error message
    Path workspaceCargoToml = tempDir.resolve("Cargo.toml");
    String workspaceContent =
        """
        [workspace]
        members = ["member1"]
        """;
    Files.writeString(workspaceCargoToml, workspaceContent);

    Path memberDir = tempDir.resolve("member1");
    Files.createDirectories(memberDir);
    Path memberCargoToml = memberDir.resolve("Cargo.toml");
    String memberContent =
        """
        [package]
        name = "member1"
        version = "1.0.0"
        edition = "2021"
        """;
    Files.writeString(memberCargoToml, memberContent);

    // Should throw exception for missing workspace lock file
    IllegalStateException exception =
        assertThrows(
            IllegalStateException.class,
            () -> Ecosystem.getProvider(memberCargoToml),
            "Should throw exception for missing workspace Cargo.lock");

    assertTrue(exception.getMessage().contains("Cargo.lock does not exist"));
    assertTrue(exception.getMessage().contains("cargo build"));

    System.out.println("✓ Missing workspace lock file validation test passed!");
  }
}
